type: rpm-ostree
install:
  - gnome-console
  - firewall-config
  - gnome-disk-utility
remove:
  - gnome-terminal
  - gnome-terminal-nautilus
  - gnome-tour
  - yelp
  - gnome-user-share
  - mod_lua
  - httpd
  - httpd-core
  - mod_http2
  - mod_dnssd
  - gnome-remote-desktop
  - libvncserver
  - malcontent-ui-libs
  - malcontent-control
